# Generated by Django 3.2.7 on 2021-09-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='photo',
            field=models.ImageField(default='cities/default.png', upload_to='cities'),
        ),
        migrations.AddField(
            model_name='cuisinetype',
            name='photo',
            field=models.ImageField(default='cuisines/default.png', upload_to='cuisines'),
        ),
        migrations.AddField(
            model_name='dish',
            name='price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='photo',
            field=models.ImageField(blank=True, default='restaurant/%Y/%m/%d', upload_to='restaurant/%Y/%m/%d'),
        ),
    ]
